Repository egc-veleta/decide, pull requests merged in 2021-12, with the labels that each got.

#3 Implementar la configuración para la Integración Continua
  .github/workflows/django.yml
  decide/decide/settings.py
  requirements.txt
Labels: high priority, conf

#4 Implementar la configuración para la Integración Continua
  .github/workflows/django.yml
  decide/decide/settings.py
  requirements.txt
Labels: high priority, conf

#5 Modificar la configuración de integración continua
  Procfile
  decide/decide/settings.py
Labels: high priority, fix, conf

#6 Modificar la configuración de integración continua
  Procfile
  decide/decide/settings.py
Labels: high priority, fix, conf

#12 Integración de las funcionalidades implementadas por el grupo 2 (M2)
  .github/ISSUE_TEMPLATE/incidencia.md
  .github/workflows/django.yml
  .gitignore
  decide/admin/templates/admin/index.html
  decide/booth/selenium/test_inicio_sin_logear.py
  decide/booth/static/booth/inicio_style.css
  decide/booth/templates/booth/inicio.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/decide/settings.py
  decide/voting/forms.py
  decide/voting/migrations/0004_voting_url.py
  decide/voting/models.py
  decide/voting/selenium/test_crear_pregunta.py
  decide/voting/templates/dichotomyform.html
  decide/voting/templates/typeform.html
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: feature, high priority

#13 Integración de las funcionalidades implementadas por el grupo 2 (M2)
  .github/ISSUE_TEMPLATE/incidencia.md
  .github/workflows/django.yml
  .gitignore
  decide/admin/templates/admin/index.html
  decide/base/templates/base.html
  decide/base/templates/inicio.html
  decide/base/views.py
  decide/booth/selenium/test_inicio_sin_logear.py
  decide/booth/static/booth/inicio_style.css
  decide/booth/static/booth/style.css
  decide/booth/static/js/grafica_visualizer.js
  decide/booth/templates/booth/booth.html
  decide/booth/templates/booth/inicio.html
  decide/booth/tests.py
  decide/booth/urls.py
  decide/booth/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/visualizer/migrations/datos_prueba.json
  decide/visualizer/templates/visualizer/inicio.html
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
  decide/voting/forms.py
  decide/voting/migrations/0004_voting_url.py
  decide/voting/models.py
  decide/voting/selenium/test_crear_pregunta.py
  decide/voting/templates/dichotomyform.html
  decide/voting/templates/typeform.html
  decide/voting/tests.py
  decide/voting/urls.py
  decide/voting/views.py
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
  requirements.txt
Labels: feature, high priority
